name: "Ideathon Cron Job Schedular"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '30 12 21 8 wed'
    
    
jobs:
  terraform_schedule:
    name: "Test Actions Schedules"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trigger Deploy workflow
        run: gh workflow run test.yml --ref main
        if: github.event.schedule == '30 12 21 8 wed'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

        
      # - name: Add Email
      #   run: git config user.email @${{ github.actor }}

      # - name: Add Username
      #   run: git config user.name @${{ github.actor }}
  
      # - name: Create Empty Commit
      #   run: git commit --allow-empty -m "Empty commit4"
  
      # - name: Push Empty Commit
      #   run: git push origin bot-defense-re
      #   env:
      #     GH_TOKEN: ${{ secrets.ACTIONS_SECRET }} 
